In [1]:
import h5py
import pandas as pd
import numpy as np
import time

from sklearn.model_selection import train_test_split
import tensorflow as tf

In [2]:
f = h5py.File('processed-pythia82-lhc13-all-pt1-50k-r1_h022_e0175_t220_nonu_withPars_truth_0.z','r')
treeArray = f['t_allpar_new'][()]

features = ['j1_costhetarel', 'j_eta', 'j1_phirel', 'j_pt', 'j1_pz','j_index']
featuresUsed = ['j1_ptrel', 'j1_etarot', 'j1_phirot', 'j1_erel', 'j1_deltaR']
pdgid = ['j_index', 'j1_pdgid']
glob = ['j_mass_mmdt', 'j_mass' ,'j_index']
labels = ['j_g', 'j_index']

features_df = pd.DataFrame(treeArray,columns=list(set(features)))
labels_df = pd.DataFrame(treeArray,columns=list(set(labels)))
df = df.reindex(features[:-1]+labels, axis=1)


NameError: name 'df' is not defined

In [ ]:
o = 0
features_df = features_df.groupby('j_index')
for name, group in features_df:
    
    break

In [ ]:
features_df

In [42]:
2*np.arctan(np.exp(1.364641))

2.6413477251815407

In [43]:
np.cos(2.6413)

-0.8774422187066925

In [51]:
df['j1_costhetarel']= df.iloc[:, 0:43].sum(axis=1)

In [52]:
df['j1_costhetarel']

0             101334.0
1             101334.0
2             101334.0
3             101334.0
4             101334.0
              ...     
5131608    300123134.0
5131609    300123134.0
5131610    300123134.0
5131611    300123134.0
5131612    300123134.0
Name: j1_costhetarel, Length: 5131613, dtype: float64

In [30]:
features_df.sum(axis = 0, skipna = True)

j1_phirel         5.895731e+02
j_eta             3.671700e+03
j1_pz            -2.484671e+04
j_pt              5.423150e+09
j1_costhetarel   -5.196702e+01
dtype: float32

In [49]:
g[]

KeyError: 'Column not found: 1'

In [4]:
pid = pd.DataFrame(treeArray,columns = pdgid)

In [5]:
pid

j_index  j1_pdgid
0           101333     130.0
1           101333     211.0
2           101333     321.0
3           101333     211.0
4           101333    -211.0
...            ...       ...
5131608  300123134     111.0
5131609  300123134     111.0
5131610  300123134     111.0
5131611  300123134     111.0
5131612  300123134     111.0

[5131613 rows x 2 columns]

In [3]:
features_df['j_index'].drop_duplicates()

0             101333
51         100073064
101        300177633
142        100188310
161        200044159
             ...    
5131388    300173707
5131417    200033311
5131447    400153985
5131486    300037743
5131530    300123134
Name: j_index, Length: 98769, dtype: int32

In [4]:
index_df = features_df.groupby(['j_index'])

In [5]:
index_df.first()

j_pt       j1_pz  j1_costhetarel  j1_phirel     j_eta
j_index                                                                
1          1089.532837 -238.826492    6.123234e-17  -0.024659 -0.402245
3          1323.108398 -467.658966    6.123234e-17  -0.033144 -0.445925
7          1623.214233  -64.350327    6.123234e-17   0.060146 -0.048563
21         1327.434937  112.867065    6.123234e-17  -0.019943  0.637988
23         1168.114624   11.454964    6.123234e-17   0.061119  0.068708
...                ...         ...             ...        ...       ...
400199939  1186.989136   67.624687    6.123234e-17  -0.075494  0.880082
400199945  1046.288330  -32.895012    6.123234e-17   0.059135 -0.209946
400199962   989.295532   73.238457    6.123234e-17  -0.250765  1.026698
400199967   725.723083   13.082801    6.123234e-17  -0.013241  0.126634
400199970   949.382874   -9.781879    6.123234e-17   0.037863 -0.041885

[98769 rows x 5 columns]

In [6]:
max_particles = 20

In [7]:
for name, group in index_df:
    print(x)
    x = group.to_numpy()
    x = np.delete(x,3,1)
    for l in x:
        print(l)

    p = p+1

[ 1.08953284e+03 -2.38826492e+02  1.00000000e+00 -2.46594101e-02
 -4.02245462e-01]
[ 1.08953284e+03 -3.70234985e+01  1.00000000e+00 -2.93168835e-02
 -4.02245462e-01]
[ 1.08953284e+03 -3.28273659e+01  1.00000000e+00 -2.02614833e-02
 -4.02245462e-01]
[ 1.08953284e+03 -2.96671181e+01  1.00000000e+00 -3.46643962e-02
 -4.02245462e-01]
[ 1.08953284e+03 -1.88448429e+01  1.00000000e+00 -2.46068090e-02
 -4.02245462e-01]
[ 1.08953284e+03 -1.67725811e+01  1.00000000e+00 -2.50142440e-02
 -4.02245462e-01]
[ 1.08953284e+03 -9.05953217e+00  1.00000000e+00 -3.17640938e-02
 -4.02245462e-01]
[ 1.08953284e+03 -7.38268423e+00  1.00000000e+00  1.84924990e-01
 -4.02245462e-01]
[ 1.08953284e+03 -8.23092365e+00  1.00000000e+00 -3.59939113e-02
 -4.02245462e-01]
[ 1.08953284e+03 -6.49501371e+00  1.00000000e+00  2.25467443e-01
 -4.02245462e-01]
[ 1.08953284e+03 -5.83619833e+00  1.00000000e+00  1.98602200e-01
 -4.02245462e-01]
[ 1.08953284e+03 -3.55707645e+00  1.00000000e+00  2.27686733e-01
 -4.02245462e-01]
[ 1.

NameError: name 'p' is not defined

In [13]:
data = np.zeros([98769,max_particles,5])
p = 0
for name, group in index_df:
    x = group.to_numpy()
    x = np.delete(x,2,1)
    g = 0
    for l in x:
        if g == 19: 
            break
        for n in range(5):
            data[p,g,n] = l[n]
        g = g+1

    p = p+1
    

In [14]:
data

array([[[ 1.08953284e+03, -2.38826492e+02,  6.12323426e-17,
         -2.46594101e-02, -4.02245462e-01],
        [ 1.08953284e+03, -3.70234985e+01, -1.00144919e-03,
         -2.93168835e-02, -4.02245462e-01],
        [ 1.08953284e+03, -3.28273659e+01,  6.44924818e-04,
         -2.02614833e-02, -4.02245462e-01],
        ...,
        [ 1.08953284e+03, -2.15238881e+00,  5.28126955e-03,
          2.52981424e-01, -4.02245462e-01],
        [ 1.08953284e+03, -2.29264808e+00, -2.41257902e-02,
         -1.21185638e-01, -4.02245462e-01],
        [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
          0.00000000e+00,  0.00000000e+00]],

       [[ 1.32310840e+03, -4.67658966e+02,  6.12323426e-17,
         -3.31439972e-02, -4.45924610e-01],
        [ 1.32310840e+03, -7.14123840e+01,  8.35500018e-14,
          1.44446135e-01, -4.45924610e-01],
        [ 1.32310840e+03, -1.09899883e+01, -1.28690124e-01,
         -1.20779283e-01, -4.45924610e-01],
        ...,
        [ 1.32310840e+03, -1.6472963

In [10]:
data

array([[[ 1.08953284e+03, -2.38826492e+02,  1.00000000e+00,
         -2.46594101e-02, -4.02245462e-01],
        [ 1.08953284e+03, -3.70234985e+01,  1.00000000e+00,
         -2.93168835e-02, -4.02245462e-01],
        [ 1.08953284e+03, -3.28273659e+01,  1.00000000e+00,
         -2.02614833e-02, -4.02245462e-01],
        ...,
        [ 1.08953284e+03, -2.15238881e+00,  1.00000000e+00,
          2.52981424e-01, -4.02245462e-01],
        [ 1.08953284e+03, -2.29264808e+00,  1.00000000e+00,
         -1.21185638e-01, -4.02245462e-01],
        [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
          0.00000000e+00,  0.00000000e+00]],

       [[ 1.32310840e+03, -4.67658966e+02,  3.00000000e+00,
         -3.31439972e-02, -4.45924610e-01],
        [ 1.32310840e+03, -7.14123840e+01,  3.00000000e+00,
          1.44446135e-01, -4.45924610e-01],
        [ 1.32310840e+03, -1.09899883e+01,  3.00000000e+00,
         -1.20779283e-01, -4.45924610e-01],
        ...,
        [ 1.32310840e+03, -1.6472963

In [19]:
labels_df = labels_df.groupby('j_index')

In [35]:
labels = np.zeros([98769])
o = 0
for name,  group in labels_df:
    x = group.to_numpy()
    labels[o] = x[0][0]
    o = o+1

In [36]:
labels

array([1., 1., 1., ..., 0., 0., 0.])

In [19]:
globdf = pd.DataFrame(treeArray, columns = glob)

In [22]:
globdf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5131613 entries, 0 to 5131612
Data columns (total 3 columns):
 #   Column       Dtype  
---  ------       -----  
 0   j_mass_mmdt  float32
 1   j_mass       float32
 2   j_index      int32  
dtypes: float32(2), int32(1)
memory usage: 58.7 MB


In [23]:
globdf.describe()

j_mass_mmdt        j_mass       j_index
count  5.131613e+06  5.131613e+06  5.131613e+06
mean   8.715534e+01  1.057106e+02  1.983574e+08
std    5.963086e+01  4.687050e+01  1.561900e+08
min    4.930874e-01  6.401100e+00  1.000000e+00
25%    3.599670e+01  7.878964e+01  1.835120e+05
50%    8.239690e+01  9.155611e+01  2.000977e+08
75%    1.300335e+02  1.407195e+02  4.000067e+08
max    4.452770e+02  4.452770e+02  4.002000e+08

In [40]:
glob = np.zeros([98769, 2])
o = 0
for name, group in globdf:
    x = group.to_numpy()
    x = np.delete(x,2,1)
    for m in range(2):
        glob[o,m] = x[0,m]
    o = o+1

In [41]:
glob


array([[ 90.77446747,  93.24835968],
       [148.98461914, 150.47558594],
       [241.29042053, 241.29042053],
       ...,
       [182.7910614 , 182.7910614 ],
       [145.66259766, 145.66259766],
       [166.74099731, 166.74099731]])

In [42]:
labels.shape

(98769,)

In [43]:
data_train, data_test, labels_train, labels_test = train_test_split(data, labels, test_size=0.50, random_state=42)


In [44]:
trash_train, trash_test, glob_train, glob_test = train_test_split(data, glob, test_size=0.50, random_state=42)

In [45]:
data_train.shape

(49384, 20, 5)

In [46]:
glob_train.shape

(49384, 2)

In [47]:
data_test.shape

(49385, 20, 5)

In [75]:
f = h5py.File('traindata5tag.h5','w')

In [76]:
f.create_dataset('data', data = data_train)


<HDF5 dataset "data": shape (49384, 20, 5), type "<f8">

In [77]:
f.create_dataset('pid', data = labels_train)

<HDF5 dataset "pid": shape (49384,), type "<f8">

In [78]:
f.create_dataset('global', data = glob_train)

<HDF5 dataset "global": shape (49384, 2), type "<f8">

In [79]:
f.keys()


<KeysViewHDF5 ['data', 'global', 'pid']>

In [62]:
f.close

<bound method File.close of <HDF5 file "traindata2tag.h5" (mode r+)>>

In [141]:
data_val, data_test, labels_val, labels_test = train_test_split(data_test, labels_test, test_size=0.50, random_state=42)


In [143]:
trash_val, trash_test, glob_val, glob_test = train_test_split(data_train, glob_test, test_size = 0.5, random_state=42)

ValueError: Found input variables with inconsistent numbers of samples: [49384, 49385]

In [6]:
f = h5py.File('traindata5tag.h5', 'r')

OSError: Unable to open file (bad object header version number)

In [130]:
f.create_dataset('data', data = data_test)


<HDF5 dataset "data": shape (24693, 20, 5), type "<f8">

In [131]:
f.create_dataset('pid', data = labels_test)


<HDF5 dataset "pid": shape (24693, 5), type "<f8">

In [132]:
f.create_dataset('global', data = glob_test)

<HDF5 dataset "global": shape (12347, 2), type "<f8">

In [3]:
k = h5py.File('test_files_qg.h5','r')

In [4]:
k.keys()


<KeysViewHDF5 ['data', 'global', 'pid']>

In [197]:
treearray = k['global']

In [198]:
treearray

<HDF5 dataset "global": shape (200000, 2), type "<f8">

In [255]:
f['data'][:]

array([[[4.53610411e-15, 4.53610411e-15, 4.53610411e-15, 4.53610411e-15,
         4.53610411e-15],
        [4.53610411e-15, 4.53610411e-15, 4.53610411e-15, 4.53610411e-15,
         4.53610411e-15],
        [4.53610411e-15, 4.53610411e-15, 4.53610411e-15, 4.53610411e-15,
         4.53610411e-15],
        ...,
        [4.53610411e-15, 4.53610411e-15, 4.53610411e-15, 4.53610411e-15,
         4.53610411e-15],
        [4.53610411e-15, 4.53610411e-15, 4.53610411e-15, 4.53610411e-15,
         4.53610411e-15],
        [4.53610411e-15, 4.53610411e-15, 4.53610411e-15, 4.53610411e-15,
         4.53610411e-15]],

       [[2.56267285e-05, 2.56267285e-05, 2.56267285e-05, 2.56267285e-05,
         2.56267285e-05],
        [2.56267285e-05, 2.56267285e-05, 2.56267285e-05, 2.56267285e-05,
         2.56267285e-05],
        [2.56267285e-05, 2.56267285e-05, 2.56267285e-05, 2.56267285e-05,
         2.56267285e-05],
        ...,
        [2.56267285e-05, 2.56267285e-05, 2.56267285e-05, 2.56267285e-05,
        

In [246]:
k['data']

<HDF5 dataset "data": shape (200000, 100, 8), type "<f8">

In [8]:
k['pid']

<HDF5 dataset "pid": shape (200000,), type "<f8">

In [248]:
f['pid']

<HDF5 dataset "pid": shape (79015,), type "<f8">

In [249]:
k['glob']

KeyError: "Unable to open object (object 'glob' doesn't exist)"

In [80]:
f = h5py.File('traindata5tag.h5')

/home/anrunw/anaconda3/envs/tfgpu/lib/python3.6/site-packages/ipykernel_launcher.py:1: H5pyDeprecationWarning: The default file mode will change to 'r' (read-only) in h5py 3.0. To suppress this warning, pass the mode you need to h5py.File(), or set the global default h5.get_config().default_file_mode, or set the environment variable H5PY_DEFAULT_READONLY=1. Available modes are: 'r', 'r+', 'w', 'w-'/'x', 'a'. See the docs for details.
  """Entry point for launching an IPython kernel.


In [69]:
f.create_dataset('pid', data = labels_train )

ValueError: Unable to create dataset (no write intent on file)

In [74]:
f.close()

In [1]:
10%10

0